# Generated by Django 5.0.7 on 2024-07-26 13:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("detection", "0002_alter_uploadalert_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadalert",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
